conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name="profile"),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name="login"),
    path('logout_user', views.logout_user, name="logout"),
]

items/urls.py
from django.urls import path

from . import views

app_name = "item"

urlpatterns = [
    path('', views.items, name="items"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('new/', views.new , name='new'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('items/', include("items.urls")),
    path('', include('core.urls')),
    path('inbox/', include('conversation.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Store(models.Model):
    image = models.ImageField(upload_to='pics/%y/%m/%d/')
    title = models.CharField(max_length=150)
    sub_title = models.CharField(max_length=150)
    
    def __Str__(self):
        return self.title
    
class UserProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length = 254)
    
    def __str__(self) -> str:
        return self.user.username

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout
from items.models import Category, Item
from .models import Store
from .forms import SignupForm
from django.contrib import messages

# Create your views here.
@login_required
def index(request):
    obj = Store.objects.all()
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html',{
        'categories': categories,
        'items': items,
        'obj':obj,
    })
    
@login_required
def profile(request):
    items = Item.objects.filter(created_by=request.user)
    
    return render(request, 'core/profile.html', {
        'items': items,
    })

def terms(request):
    return render(request, 'core/term_of_use.html')

def privacy(request):
    return render(request, 'core/privacy_policy.html')

def about(request):
    return render(request, 'core/about.html')

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()
            
        
    form = SignupForm()
    return render(request, 'core/signup.html', {
        'form':form
    })
    
# @login_required
# def profile_index(request):
#     items = Item.objects.filter(created_by=request.user)
    
#     return render(request, 'core/profile.html', {
#         'items': items,
#     })


def logout_user(request):
    logout(request)
    messages.success(request, ("You were loged out"))
    return redirect('core:index')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h1>The about page</h1>
{% endblock %}

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/sketchy/bootstrap.min.css">

        <title>{% block title %}{% endblock %} | Treasure Market</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-3xl font-semibold">Treasure Market</a>
        
            <div class="flex space-x-6 items-center">
                <a href="{% url 'item:new' %}" class="text-xl font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'item:items' %}" class="text-xl font-semibold hover:text-gray-500">Browse</a>
        
                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-xl font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-xl font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
                    <div class="relative w-10 h-10 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
                        <a href="{% url 'core:profile' %}" class="relative w-10 h-10 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
                            <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
                            </svg>
                        </a>
                    </div>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-xl font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-xl font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>
               

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 mt-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-white">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-white">Contact</a></li>
                    <li><a href="{% url 'core:privacy'%}" class="text-lg text-teal-500 hover:text-white">Privacy policy</a></li>
                    <li><a href="{% url 'core:terms'%}" class="text-lg text-teal-500 hover:text-white">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-6 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {% for item in items %}
                <div class="flex flex-col h-full">
                    <a href="{% url 'item:detail' item.id %}" class="flex flex-col h-full">
                        <div class="relative">
                            <img src="{{ item.image.url }}" class="w-full h-48 md:h-64 lg:h-72 object-cover object-center rounded-t-xl">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl flex-grow flex flex-col justify-between">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        
        
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-6 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
                        <div class="btn shadow-[0_9px_0_rgb(0,0,0)] hover:shadow-[0_4px_0px_rgb(0,0,0)] text-black bg-white ease-out hover:translate-y-1 transition-all rounded">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{%block content %}
<div class="w1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">
        Log in
    </h1>
    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">
                Username
            </label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">
                Password
            </label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounnded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">  
            Submit
        </button>
    </form>
</div>
{% endblock %}

core/templates/core/privacy_policy.html
{% extends 'core/base.html' %}

{% block title %}Privacy policy{% endblock %}

{% block content %}
    <h1>The privacy policy page</h1>
{% endblock %}

core/templates/core/profile.html
{% extends 'core/base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

    <div class="grid grid-cols-2 gap-3 bg-gray-100 rounded-xl" style="height: 100px;">

        <div class="mt-2 relative w-20 h-20 overflow-hidden bg-black-500 rounded-full dark:bg-black-600 ">
            <svg class="absolute w-15 h-15 text-black-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
            </svg>
        </div>
        
        <div class="mt-3"> 
            <h1 class="text-white-500 text-3xl inline-block align-middle">Name: {{ request.user.username }}</h1><br>
            <h1 class="text-white-500 text-3xl inline-block align-middle">
                Account: {{request.user.email}}
            </h1>
        </div>
    </div>




    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My items</h2>

        <div class="grid grid-cols-3 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {% for item in items %}
                <div class="flex flex-col h-full">
                    <a href="{% url 'item:detail' item.id %}" class="flex flex-col h-full">
                        <div class="relative">
                            <img src="{{ item.image.url }}" class="w-full h-48 md:h-64 lg:h-72 object-cover object-center rounded-t-xl">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl flex-grow flex flex-col justify-between">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{%block content %}
<div class="w1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">
        Sign up
    </h1>
    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">
                Username
            </label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">
                Email
            </label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">
                Password
            </label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">
                Repeat password
            </label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounnded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">  
            Submit
        </button>
    </form>
</div>
{% endblock %}

core/templates/core/term_of_use.html
{% extends 'core/base.html' %}

{% block title %}Term of use{% endblock %}

{% block content %}
    <h1>The term of use page</h1>
{% endblock %}